using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

public static class Values
{
    public static readonly Dictionary<string, string> FlagPaths = new Dictionary<string, string>
    {
        {"Velká Británie", @"vlajky\img1.jpg"},
        {"Česká republika", @"vlajky\img2.jpg"},
        {"Rakousko", @"vlajky\img3.jpg"},
        {"Dánsko", @"vlajky\img4.jpg"},
        {"Francie", @"vlajky\img5.jpg"},
        {"Řecko", @"vlajky\img6.jpg"},
        {"Makedonie", @"vlajky\img7.jpg"},
        {"Kanada", @"vlajky\img8.jpg"},
        {"Itálie", @"vlajky\img9.jpg"},
        {"Nizozemsko", @"vlajky\img10.jpg"},
        {"Lucembursko", @"vlajky\img11.jpg"},
        {"Litva", @"vlajky\img12.jpg"},
        {"Rusko", @"vlajky\img13.jpg"},
        {"Rumunsko", @"vlajky\img14.jpg"},
        {"Španělsko", @"vlajky\img15.jpg"},
        {"Švédsko", @"vlajky\img16.jpg"},
        {"Švýcarsko", @"vlajky\img17.jpg"},
    };

    public static readonly Dictionary<string, string> ColorFlagPaths = new Dictionary<string, string>
    {
        {"Velká Británie", @"barevne_vlajky\img1.png"},
        {"Česká republika", @"barevne_vlajky\img2.png"},
        {"Rakousko", @"barevne_vlajky\img3.png"},
        {"Dánsko", @"barevne_vlajky\img4.png"},
        {"Francie", @"barevne_vlajky\img5.png"},
        {"Řecko", @"barevne_vlajky\img6.png"},
        {"Makedonie", @"barevne_vlajky\img7.png"},
        {"Kanada", @"barevne_vlajky\img8.png"},
        {"Itálie", @"barevne_vlajky\img9.png"},
        {"Nizozemsko", @"barevne_vlajky\img10.png"},
        {"Lucembursko", @"barevne_vlajky\img11.png"},
        {"Litva", @"barevne_vlajky\img12.png"},
        {"Rusko", @"barevne_vlajky\img13.png"},
        {"Rumunsko", @"barevne_vlajky\img14.png"},
        {"Španělsko", @"barevne_vlajky\img15.png"},
        {"Švédsko", @"barevne_vlajky\img16.png"},
        {"Švýcarsko", @"barevne_vlajky\img17.png"},
    };

    public static readonly Dictionary<string, string[]> FlagColorList = new Dictionary<string, string[]>
    {
        {"Velká Británie", new string[] { "červená", "modrá", "bílá" } },
        {"Česká republika", new string[] { "červená", "modrá", "bílá" } },
        {"Rakousko", new string[] { "červená", "modrá", "bílá" } },
        {"Dánsko", new string[] { "červená", "modrá", "bílá" } },
        {"Francie", new string[] { "červená", "modrá", "bílá" } },
        {"Řecko", new string[] { "červená", "modrá", "bílá" } },
        {"Makedonie", new string[] { "červená", "modrá", "bílá" } },
        {"Kanada", new string[] { "červená", "modrá", "bílá" } },
        {"Itálie", new string[] { "červená", "modrá", "bílá" } },
        {"Nizozemsko", new string[] { "červená", "modrá", "bílá" } },
        {"Lucembursko", new string[] { "červená", "modrá", "bílá" } },
        {"Litva", new string[] { "červená", "modrá", "bílá" } },
        {"Rusko", new string[] { "červená", "modrá", "bílá" } },
        {"Rumunsko", new string[] { "červená", "modrá", "bílá" } },
        {"Španělsko", new string[] { "červená", "modrá", "bílá" } },
        {"Švédsko", new string[] { "červená", "modrá", "bílá" } },
        {"Švýcarsko", new string[] { "červená", "modrá", "bílá" } },
    };

    public static readonly Dictionary<string, string> ColorNames = new Dictionary<string, string>
    {
        { "Red", "červená" },
        { "Maroon", "kaštanová" },
        { "Black", "černá" },
        { "Yellow", "žlutá" },
        { "Olive", "olivová" },
        { "Lime", "limetková" },
        { "Green", "zelená" },
        { "Teal", "zelenomodrá" },
        { "Gray", "šedá" },
        { "Aqua", "azurová" },
        { "Blue", "modrá" },
        { "Navy", "námořnická modrá" },
        { "Silver", "světle šedá" },
        { "Purple", "světle vínová" },
        { "Fuchsia", "fuksiová" },
        { "White", "bílá" },
        { "ffff8080", "růžová" },
        { "ff804040", "tmavě červená" },
        { "ff400000", "hluboká červená" },
        { "ffffff80", "světle žlutá" },
        { "ffff8040", "oranžová" },
        { "ffff8000", "oranžově žlutá" },
        { "ff804000", "hnědá" },
        { "ff80ff80", "světle zelená" },
        { "ff80ff00", "světle žlutě zelená" },
        { "ff004000", "tmavě zelená" },
        { "ff808040", "olivová" },
        { "ff00ff80", "jasně zelená" },
        { "ff00ff40", "jasně zelená" },
        { "ff008040", "jasně zelená" },
        { "ff004040", "tmavě zelená" },
        { "ff80ffff", "světle azurová" },
        { "ff004080", "tmavě azurová" },
        { "ff408080", "azurová" },
        { "ff0080ff", "jasně azurová" },
        { "ff0080c0", "tyrkysová" },
        { "ff8080ff", "světle fialová" },
        { "ff0000a0", "tmavě modrá" },
        { "ff000040", "tmavě modrá" },
        { "ffff80c0", "růžová" },
        { "ff8080c0", "fialová" },
        { "ff800040", "vínová" },
        { "ff400040", "tmavě vínová" },
        { "ffff80ff", "růžová" },
        { "ffff0080", "sytě růžová" },
        { "ff8000ff", "jasně fialová" },
        { "ff400080", "tmavě fialová" },
    };
}
